apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: soat-api-key-vault
spec:
  provider: azure
  secretObjects:
    - secretName: soat-api-runtime
      type: Opaque
      data:
        - objectName: database-url-__ENVIRONMENT__
          key: DATABASE_URL
        - objectName: jwt-secret-__ENVIRONMENT__
          key: JWT_SECRET
        - objectName: jwt-client-secret-__ENVIRONMENT__
          key: JWT_CLIENT_SECRET
        - objectName: admin-username-__ENVIRONMENT__
          key: ADMIN_USERNAME
        - objectName: admin-password-hash-__ENVIRONMENT__
          key: ADMIN_PASSWORD_HASH
        - objectName: mail-host-__ENVIRONMENT__
          key: MAIL_HOST
        - objectName: mail-port-__ENVIRONMENT__
          key: MAIL_PORT
        - objectName: mail-user-__ENVIRONMENT__
          key: MAIL_USER
        - objectName: mail-pass-__ENVIRONMENT__
          key: MAIL_PASS
        - objectName: mail-from-__ENVIRONMENT__
          key: MAIL_FROM
        - objectName: webhook-secret-__ENVIRONMENT__
          key: WEBHOOK_SECRET
        - objectName: app-url-__ENVIRONMENT__
          key: APP_URL
        - objectName: new-relic-license-key
          key: NEW_RELIC_LICENSE_KEY
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: __API_WORKLOAD_CLIENT_ID__
    keyvaultName: __KEY_VAULT_NAME__
    tenantId: __AZURE_TENANT_ID__
    objects: |
      array:
        - |
          objectName: database-url-__ENVIRONMENT__
          objectType: secret
        - |
          objectName: jwt-secret-__ENVIRONMENT__
          objectType: secret
        - |
          objectName: jwt-client-secret-__ENVIRONMENT__
          objectType: secret
        - |
          objectName: admin-username-__ENVIRONMENT__
          objectType: secret
        - |
          objectName: admin-password-hash-__ENVIRONMENT__
          objectType: secret
        - |
          objectName: mail-host-__ENVIRONMENT__
          objectType: secret
        - |
          objectName: mail-port-__ENVIRONMENT__
          objectType: secret
        - |
          objectName: mail-user-__ENVIRONMENT__
          objectType: secret
        - |
          objectName: mail-pass-__ENVIRONMENT__
          objectType: secret
        - |
          objectName: mail-from-__ENVIRONMENT__
          objectType: secret
        - |
          objectName: webhook-secret-__ENVIRONMENT__
          objectType: secret
        - |
          objectName: app-url-__ENVIRONMENT__
          objectType: secret
        - |
          objectName: new-relic-license-key
          objectType: secret
