apiVersion: v1
kind: ServiceAccount
metadata:
  name: soat-api
  labels:
    app.kubernetes.io/name: soat-api
    app.kubernetes.io/part-of: soat
  annotations:
    azure.workload.identity/client-id: __API_WORKLOAD_CLIENT_ID__
